### ISSUE TITLE
WebJars update request: jspdf and plugins 

### ISSUE THREAD

**Issue by medonja** [webjars/jspdf#2]
Hi,

would it be possible to update jspdf as a classical WebJar since the current version does not setup the requirejs path properly and also does not include any of the standard plugins (https://github.com/MrRio/jsPDF/tree/master/plugins)? It would be quite handy to have those scripts as a classical WebJar.

Thanks,
Marko

**Comment by medonja** [comment]
Thanks! I've tested it right now, there seems to be a small bug.. When I try to go with the new version, I get an angular.module not defined error.... :-/

**Comment by jamesward** [comment]
Sounds like you need to add an Angular dependency.  But I'm not sure which version.
